### ISSUE TITLE
Remove already accepted ontologies from config

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/obo-nor.github.io#24]
1. Find out which ontologies are already accepted
2. Remove them from the config
3. Assign to me

**Comment by pfabry** [comment]
- I assume that the best way to find which ontologies are already accepted is to check for .md files in OBOFoundry.github.io/ontology.
- Even if there are several ontologies to remove, I propose to make a PR for each ontology.
- What is the actual status of vario ? Does Probationary means that it must stay in the NOR dashboard?

**Comment by matentzn** [comment]
> I assume that the best way to find which ontologies are already accepted is to check for .md files in OBOFoundry.github.io/ontology.

Yes!

> Even if there are several ontologies to remove, I propose to make a PR for each ontology. 

Thats ok, your call to make!

> What is the actual status of vario ? Does Probationary means that it must stay in the NOR dashboard?

Politics and unfinished business: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2120

Right now, nothing for you to do here. We will see during future calls how to handle. The probationary status [has been rejected](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2121), but we still don't know if re-activation requires re-review. 

The standing position is that reactivation at least requires OBO Dashboard to pass.

**Comment by matentzn** [comment]
> EDIT: It seems I can't assign PR?

Will take care of that later this week.

**Comment by pfabry** [comment]
Older ontologies removed. Closing the issue.
